export default [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialServiceFee",
        type: "uint256",
      },
      { internalType: "uint256", name: "_delay", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "InsufficientDelay", type: "error" },
  { inputs: [], name: "InsufficientPaymentForService", type: "error" },
  { inputs: [], name: "NoFundsToWithdraw", type: "error" },
  { inputs: [], name: "NoTokensToWithdraw", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "ZeroFee", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "backupContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "deployer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "userHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "metaId",
        type: "bytes32",
      },
    ],
    name: "DeployedBackupContract",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "MIN_DELAY",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "creatorAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "delay",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_beneficiaryAddress0",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "_beneficiaryShares0",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "_beneficiaryAddress1",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "_beneficiaryShares1",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "_beneficiaryAddress2",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "_beneficiaryShares2",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "_beneficiaryAddress3",
        type: "address",
      },
      { internalType: "address", name: "_tokenAddress", type: "address" },
      { internalType: "address", name: "_executor", type: "address" },
      { internalType: "bytes32", name: "_userHash", type: "bytes32" },
      { internalType: "bytes32", name: "_metaId", type: "bytes32" },
    ],
    name: "deployBackupContract",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "serviceFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newCreatorAddress",
        type: "address",
      },
    ],
    name: "setCreator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newServiceFee", type: "uint256" },
    ],
    name: "setFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_receiver", type: "address" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_receiver", type: "address" },
      { internalType: "address", name: "_tokenAddress", type: "address" },
    ],
    name: "withdrawToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
